---
abstract: 'a simulator of random shotgun and amplicon sequence libraries'
author:
  - 'Florent Angly <florent.angly at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Grinder
no_index:
  directory:
    - inc
    - t
requires:
  Bio::SeqIO: 0
  Getopt::Euclid: 0
  Math::Random::MT::Perl: 1.06
  perl: 5.6.0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.3.3
