#! /usr/bin/env perl

# Copyright 2009-2010 Florent Angly <florent.angly@gmail.com> under GNU GPLv3 license

# Grinder is a program to create artificial random shotgun and amplicon sequence
# libraries based on reference genomes in a FASTA file. Features include:
#   * shotgun library or amplicon library
#   * arbitrary read length distribution and number of reads
#   * simulation of mutations / sequencing errors
#   * support for creating paired end datasets
#   * specific rank-abundance settings or manually given abundance for each genome
#   * creation of datasets with a given richness (alpha diversity)
#   * independent datasets can share a variable number of genomes (beta diversity)
#  * modeling of the bias created by different genome lengths
#
# This program provides a command-line and API interface. This has the advantage
# that you can automate the creation of a large number of artificial metagenomes,
# pyrotag datasets, or shotgun sequencing projects easily.

# Grinder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# Grinder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with Grinder.  If not, see <http://www.gnu.org/licenses/>.


use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin";
use Grinder;
Grinder::Grinder(@ARGV);
exit;

